"""Add transaction table

Revision ID: 4b32bc7afb72
Revises: 44d5442b2ac8
Create Date: 2026-01-28 01:40:15.986149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b32bc7afb72'
down_revision: Union[str, Sequence[str], None] = '44d5442b2ac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('gateway_order_id', sa.String(), nullable=True),
    sa.Column('gateway_payment_id', sa.String(), nullable=True),
    sa.Column('gateway_signature', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ticket_pnr', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['ticket_pnr'], ['tickets.pnr'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_payment_id')
    )
    op.create_index(op.f('ix_transactions_gateway_order_id'), 'transactions', ['gateway_order_id'], unique=True)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_gateway_order_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
