"""Add average_speed column to trains

Revision ID: 5734d6f476b6
Revises: 
Create Date: 2026-01-25 00:57:39.921547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5734d6f476b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'from_seq',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bookings', 'to_seq',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.drop_constraint(op.f('bookings_pnr_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'tickets', ['pnr'], ['pnr'])
    op.alter_column('route_stations', 'sequence_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('route_stations', 'distance_from_start',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('route_stations_route_id_sequence_number_key'), 'route_stations', type_='unique')
    op.create_index(op.f('ix_route_stations_id'), 'route_stations', ['id'], unique=False)
    op.drop_constraint(op.f('route_stations_route_id_fkey'), 'route_stations', type_='foreignkey')
    op.create_foreign_key(None, 'route_stations', 'routes', ['route_id'], ['id'])
    op.alter_column('routes', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('routes', 'distance',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.alter_column('seats', 'number',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.create_index(op.f('ix_seats_id'), 'seats', ['id'], unique=False)
    op.drop_constraint(op.f('seats_train_id_fkey'), 'seats', type_='foreignkey')
    op.create_foreign_key(None, 'seats', 'trains', ['train_id'], ['id'])
    op.alter_column('stations', 'code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('stations', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('stations', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(op.f('stations_code_key'), 'stations', type_='unique')
    op.create_index(op.f('ix_stations_code'), 'stations', ['code'], unique=True)
    op.create_index(op.f('ix_stations_id'), 'stations', ['id'], unique=False)
    op.alter_column('tickets', 'trip_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_index(op.f('ix_tickets_pnr'), 'tickets', ['pnr'], unique=False)
    op.alter_column('train_daily_routes', 'day_of_week',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('train_daily_routes', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.drop_constraint(op.f('train_daily_routes_train_id_day_of_week_key'), 'train_daily_routes', type_='unique')
    op.create_index(op.f('ix_train_daily_routes_id'), 'train_daily_routes', ['id'], unique=False)
    op.drop_constraint(op.f('train_daily_routes_train_id_fkey'), 'train_daily_routes', type_='foreignkey')
    op.create_foreign_key(None, 'train_daily_routes', 'trains', ['train_id'], ['id'])
    op.add_column('trains', sa.Column('average_speed', sa.Integer(), nullable=True))
    op.alter_column('trains', 'number',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('trains', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(op.f('trains_number_key'), 'trains', type_='unique')
    op.create_index(op.f('ix_trains_id'), 'trains', ['id'], unique=False)
    op.create_index(op.f('ix_trains_number'), 'trains', ['number'], unique=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(op.f('users_hashed_password_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint(op.f('users_hashed_password_key'), 'users', ['hashed_password'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index(op.f('ix_trains_number'), table_name='trains')
    op.drop_index(op.f('ix_trains_id'), table_name='trains')
    op.create_unique_constraint(op.f('trains_number_key'), 'trains', ['number'], postgresql_nulls_not_distinct=False)
    op.alter_column('trains', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('trains', 'number',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_column('trains', 'average_speed')
    op.drop_constraint(None, 'train_daily_routes', type_='foreignkey')
    op.create_foreign_key(op.f('train_daily_routes_train_id_fkey'), 'train_daily_routes', 'trains', ['train_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_train_daily_routes_id'), table_name='train_daily_routes')
    op.create_unique_constraint(op.f('train_daily_routes_train_id_day_of_week_key'), 'train_daily_routes', ['train_id', 'day_of_week'], postgresql_nulls_not_distinct=False)
    op.alter_column('train_daily_routes', 'start_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('train_daily_routes', 'day_of_week',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_index(op.f('ix_tickets_pnr'), table_name='tickets')
    op.alter_column('tickets', 'trip_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_index(op.f('ix_stations_id'), table_name='stations')
    op.drop_index(op.f('ix_stations_code'), table_name='stations')
    op.create_unique_constraint(op.f('stations_code_key'), 'stations', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('stations', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('stations', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('stations', 'code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_constraint(None, 'seats', type_='foreignkey')
    op.create_foreign_key(op.f('seats_train_id_fkey'), 'seats', 'trains', ['train_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_seats_id'), table_name='seats')
    op.alter_column('seats', 'number',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_index(op.f('ix_routes_id'), table_name='routes')
    op.alter_column('routes', 'distance',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('routes', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'route_stations', type_='foreignkey')
    op.create_foreign_key(op.f('route_stations_route_id_fkey'), 'route_stations', 'routes', ['route_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_route_stations_id'), table_name='route_stations')
    op.create_unique_constraint(op.f('route_stations_route_id_sequence_number_key'), 'route_stations', ['route_id', 'sequence_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('route_stations', 'distance_from_start',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('route_stations', 'sequence_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_pnr_fkey'), 'bookings', 'tickets', ['pnr'], ['pnr'], ondelete='CASCADE')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.alter_column('bookings', 'to_seq',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'from_seq',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
