"""replacing day_of_week with date in dailyTrainRoute class

Revision ID: f4e811cd6cca
Revises: 5734d6f476b6
Create Date: 2026-01-25 13:44:03.489337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4e811cd6cca'
down_revision: Union[str, Sequence[str], None] = '5734d6f476b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('train_daily_routes', sa.Column('date', sa.Date(), nullable=True))
    op.drop_column('train_daily_routes', 'day_of_week')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('train_daily_routes', sa.Column('day_of_week', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('train_daily_routes', 'date')
    # ### end Alembic commands ###
